//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3473CFD8D22A7E33AD5E920D58A6E4541DB9E32995CF2125C7_pimgpsh_fullsize_distr {
            get {
                object obj = ResourceManager.GetObject("^3473CFD8D22A7E33AD5E920D58A6E4541DB9E32995CF2125C7^pimgpsh_fullsize_distr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _38EB41295143523907590A19274BDF336E452548FC75FECCDF_pimgpsh_fullsize_distr {
            get {
                object obj = ResourceManager.GetObject("^38EB41295143523907590A19274BDF336E452548FC75FECCDF^pimgpsh_fullsize_distr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3F15455D9068D71E77E9F35DE1A89E88BC286A0DCF79A422AE_pimgpsh_fullsize_distr {
            get {
                object obj = ResourceManager.GetObject("^3F15455D9068D71E77E9F35DE1A89E88BC286A0DCF79A422AE^pimgpsh_fullsize_distr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _874134312FBFA36EAD70F07C114743142DCAA4E62FEE816B66_pimgpsh_fullsize_distr {
            get {
                object obj = ResourceManager.GetObject("^874134312FBFA36EAD70F07C114743142DCAA4E62FEE816B66^pimgpsh_fullsize_distr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _D5E30543C7C8D673547D8053A92F6A998ABE29AB7E4645DDFC_pimgpsh_fullsize_distr {
            get {
                object obj = ResourceManager.GetObject("^D5E30543C7C8D673547D8053A92F6A998ABE29AB7E4645DDFC^pimgpsh_fullsize_distr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _F9C0B2E823C10B619FFF6CCBF8B0015056E0130AF4889F43CB_pimgpsh_fullsize_distr {
            get {
                object obj = ResourceManager.GetObject("^F9C0B2E823C10B619FFF6CCBF8B0015056E0130AF4889F43CB^pimgpsh_fullsize_distr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap welshfgt {
            get {
                object obj = ResourceManager.GetObject("welshfgt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap welshwatermark {
            get {
                object obj = ResourceManager.GetObject("welshwatermark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
